### ISSUE TITLE
Keyboard controls

### ISSUE THREAD

**Issue by francisrstokes** [manmon42/lljsvm-ide#1]
It would be great to be able to advance the debugger with keyboard controls, instead of only with the step button.

**Comment by maxostarr** [comment]
I've implemented a first draft version of this feature. Currently, it requires that you click the top bar area to give it focus and then it will step when the enter key is pressed.

**Comment by francisrstokes** [comment]
Is this for accessibility reasons/keeping the tabIndex sane?

**Comment by maxostarr** [comment]
Originally that was pretty much the reason for implementing it how I did. However, looking into it further, I found a way to add a global event listener which is much cleaner. Now just hitting any Enter key anywhere on the page triggers a step. I'm not sure how I missed this the first time.
