### ISSUE TITLE
Display the assembly instruction

### ISSUE THREAD

**Issue by francisrstokes** [manmon42/lljsvm-ide#2]
With a lookup table, that maps instruction opcodes to named instructions, and what the arguments are, you could display the assembly code for each instruction.

Something like:

```javascript
[
  {
    opcode: 0x17,
    name: 'psh',
    args: [
      'literal16'
    ]
  },
  {
    opcode: 0x18,
    name: 'psh',
    args: [
      'register'
    ]
  },
  ...
]
```

**Comment by maxostarr** [comment]
I've finished the first draft of this feature. Currently it parses the machine code from the values in memory from 0x0000 to 0x0100, the window of the memory display pannel. This could be expanded or customized to end on a 'clean exit' opcode.

**Comment by francisrstokes** [comment]
Really nice - I like that it visually shows different code regions.

What do you think of a user being able to select a start and end point to analyze in the editor somehow? So you could potentially try to read any region as code? That would be useful in programs that start later in memory, or are very spread out.

**Comment by maxostarr** [comment]
Sure thing! Just committed the change. The code updates live with user changes to the window.
