### ISSUE TITLE
Run code

### ISSUE THREAD

**Issue by francisrstokes** [manmon42/lljsvm-ide#3]
In addition to step, you could have a run button, that would automatically step the code at a configurable speed. In this mode, if you encountered a BRK (breakpoint) instruction, or a breakpoint set in the debugger, you could switch back to single step mode and pause execution.

**Comment by maxostarr** [comment]
I've finished the first draft of this feature. Currently, the operation is fairly self-explanatory. There's a 'run speed' input box in the top bar and a corrosponding run button. The button changes state based on the weather the machine is running or not.
