### ISSUE TITLE
Breakpoints

### ISSUE THREAD

**Issue by francisrstokes** [manmon42/lljsvm-ide#4]
Related to #3 , you could click on certain memory addresses and set breakpoints. When running the code, if a breakpoint was encountered, execution would stop and allow you to analyze the state of the machine.

**Comment by maxostarr** [comment]
I've finished the first draft of this feature. Currently, it only works for selected lines in the parsed machine code. (#2). Clicking on any given line toggles whether the machine will break on that line. Right now there's not a 'resume' feature, you need to manually step past the breakpoint at least one instruction to continue operation.

**Comment by francisrstokes** [comment]
Very cool man - this is great!
